{% set name = "ldblockshow" %}
{% set version = "1.26" %}
{% set sha256 = "54eac2914beaabe19fc9f22c178068cc7345e9253bc89c02049e66d383c5d579" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/BGI-shenzhen/LDBlockShow/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - perl
    - zlib
  run:
    - perl-svg
    - plink
    - zlib

about:
  home: https://github.com/BGI-shenzhen/LDBlockShow
  license: MIT
  license_file: LICENSE
  summary: a tool for showing linkage disequilibrium heatmaps from variant call format (VCF) files

test:
  commands:
    - "LDBlockShow 2>&1 | grep 'Usage: LDBlockShow'"

extra:
  identifiers:
    - biotools:ldblockshow
